project:
  type: website
  render:
    - "./*.Rmd"
  post-render:
    - quarto render --profile public assignments
    - cp -r assignments/assignments _site

website:
  title: "Bayesian Data Analysis course"
  navbar:
    title: "Bayesian Data Analysis course"
    left:
      - text: "Material"
        href: index.html
      - text: "Aalto 2024"
        href: Aalto2024.html
      - text: "BDA3 notes"
        href: BDA3_notes.html
      - text: "Assignments"
        href: assignments.html
      - text: "Project"
        href: project.html
      - text: "Demos"
        href: demos.html
      - text: "FAQ"
        href: FAQ.html

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc_collapse: false
    toc_depth: 3
    toc_float: true
